services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - lab
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'America/Sao_Paulo'
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
      FTLCONF_dns_listeningMode: 'all'
    cap_add:
      - SYS_TIME
      - SYS_NICE
    volumes:
      - ./docker/etc-pihole:/etc/pihole
    restart: unless-stopped
    expose:
      - "80"
      - "443"
  
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: ${VAULTWARDEN_DOMAIN}
      SINGUPS_ALLOWED: "true"
    networks:
      - lab
    volumes:
      - ./docker/vw-data:/data
    expose:
      - "80"
      - "443"

  nginx:
    container_name: nginx_reverse
    image: nginx:latest
    restart: unless-stopped
    environment:
      DOMAIN_1: ${DOMAIN_1}
      DOMAIN_2: ${DOMAIN_2}
      DOMAIN_3: ${DOMAIN_3}
      DOMAIN_4: ${DOMAIN_4}
      env: "$" # in order to still get the nginx built-in variables working, do not remove
    volumes:
      - ./docker/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./docker/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - lab
    depends_on:
      - pihole
      - vaultwarden
    entrypoint: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

networks:
  lab:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
