services:
  certbot:
    container_name: certbot
    image: serversideup/certbot-dns-cloudflare
    volumes:
      - cert_data:/etc/letsencrypt
    networks:
      - local
    environment:
      CLOUDFLARE_API_TOKEN: "${CLOUDFLARE_API_TOKEN}"
      CERTBOT_EMAIL: "${CERTBOT_EMAIL}"
      CERTBOT_DOMAINS: "${CERTBOT_DOMAINS}"
      CERTBOT_KEY_TYPE: "rsa"
      CLOUDFLARE_PROPAGATION_SECONDS: 60
    dns:
      - 172.20.0.2 #pihole ip on local
    restart: 
      unless-stopped

volumes:
  cert_data:
    external: true

networks:
  local:
    external: true
