services:
  proxy:
    image: itzg/mc-router
    container_name: minecraft_proxy
    environment:
      MAPPING: |
        minecraft.${DOMAIN}=minecraft-vanilla:25565
        mods.${DOMAIN}=minecraft-mods:25565
      SIMPLIFY_SRV: "true"
    networks:
      - local
    depends_on:
      - minecraft-mods
      - minecraft-vanilla
    restart: unless-stopped
  minecraft-mods:
    image: openjdk:22
    container_name: minecraft_mods
    working_dir: /data
    command: sh start.sh
    networks:
      - local
    volumes:
      - "./fabric:/data"
    stdin_open: true
    tty: true
    restart: unless-stopped
  minecraft-vanilla:
    image: openjdk:22
    container_name: minecraft_vanilla
    working_dir: /data
    command: sh start.sh
    networks:
      - local
    volumes:
      - "./vanilla:/data"
    stdin_open: true
    tty: true
    restart: unless-stopped

networks:
  local:
    external: true