services:
  minecraft-xaolins:
    image: openjdk:22
    container_name: minecraft_xaolins
    working_dir: /data
    command: sh start.sh
    networks:
      - local
    volumes:
      - "./paper:/data"
    stdin_open: true
    tty: true
    restart: unless-stopped
  minecraft-vanilla:
    image: openjdk:22
    container_name: minecraft_vanilla
    working_dir: /data
    command: sh start.sh
    networks:
      - local
    volumes:
      - "./paper-vanilla:/data"
    stdin_open: true
    tty: true
    restart: unless-stopped

networks:
  local:
    external: true

volumes:
  cert_data:
    external: true
