services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      lab:
        ipv4_address: ${PIHOLE_IPV4_ADDRESS}
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "443:443"
      - "80:80"
    environment:
      TZ: 'America/Sao_Paulo'
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
    cap_add:
      - SYS_TIME
      - SYS_NICE
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./resolv.conf:/etc/resolv.conf
    restart: unless-stopped

networks:
  lab:
    external: true
